---
title: "EDA Project Part 3"
author: "Sean Anthony"
date: "February 17, 2016"
output: html_document
---

```{r}
install.packages('ggplot2')
library(ggplot2)
data(diamonds)
summary(diamonds)
setwd("/Users/sa1251/Documents/eda-project/eda-project")
getwd()

```


```{r}
# Create a histogram of diamond prices.
# Facet the histogram by diamond color
# and use cut to color the histogram bars.

# The plot should look something like this.
# http://i.imgur.com/b5xyrOu.jpg

# Had issues with scale_fill_brewer function, so left colors as default. 
ggplot(aes(x = price), data = diamonds) +
  geom_histogram(aes(color = cut)) + facet_wrap(~color) + scale_x_log10()
ggsave('price_facet_color.png')
```


```{r}
# Create a scatterplot of diamond price vs.
# table and color the points by the cut of
# the diamond.

# The plot should look something like this.
# http://i.imgur.com/rQF9jQr.jpg

ggplot(aes(x = table, y = price), data = diamonds) + 
  geom_point(aes(color = cut)) + scale_color_brewer(type = 'qual') +
  scale_x_continuous(limits = c(50, 80), breaks = seq(50, 80, 2))
ggsave('color_by_cut.png')
```

```{r}
# Create a scatterplot of diamond price vs.
# volume (x * y * z) and color the points by
# the clarity of diamonds. Use scale on the y-axis
# to take the log10 of price. You should also
# omit the top 1% of diamond volumes from the plot.

# Note: Volume is a very rough approximation of
# a diamond's actual volume.

# The plot should look something like this.
# http://i.imgur.com/excUpea.jpg

diamonds$diamond_volume <- (diamonds$x * diamonds$y * diamonds$z)
summary(diamonds$diamond_volume)

ggplot(aes(x = diamond_volume, y = price), data = diamonds) + 
  geom_point(aes(color = clarity)) + 
  xlim(0.00001, quantile(diamonds$diamond_volume, 0.99)) +
  scale_y_log10() + scale_color_brewer(type = 'div')
ggsave('log10.png')
```


```{r}
# Your task is to create a new variable called 'prop_initiated'
# in the Pseudo-Facebook data set. The variable should contain
# the proportion of friendships that the user initiated.

pf <- read.csv('pseudo_facebook.tsv', sep = '\t')

pf$prop_initiated <- (pf$friendships_initiated / pf$friend_count)
```


```{r}
# Create a line graph of the median proportion of
# friendships initiated ('prop_initiated') vs.
# tenure and color the line segment by
# year_joined.bucket.

# The plot should look something like this.
# http://i.imgur.com/vNjPtDh.jpg
# OR this
# http://i.imgur.com/IBN1ufQ.jpg

pf$year_joined <- floor(2014 - pf$tenure / 365)
pf$year_joined.bucket <- cut(pf$year_joined, breaks = c(2004, 2009, 2011, 2012, 2014))

ggplot(aes(x = tenure, y = prop_initiated), data = pf) +
  geom_line(aes(color = year_joined.bucket),
            stat = 'summary', fun.y = median)
ggsave('linegraph.png')
```


```{r}
# Smooth the last plot you created of
# of prop_initiated vs tenure colored by
# year_joined.bucket. You can bin together ranges
# of tenure or add a smoother to the plot.

ggplot(aes(x = tenure, y = prop_initiated), data = pf) +
  geom_smooth(aes(color = year_joined.bucket))
ggsave('smooth.png')
```


```{r}
# Create a scatter plot of the price/carat ratio
# of diamonds. The variable x should be
# assigned to cut. The points should be colored
# by diamond color, and the plot should be
# faceted by clarity.

# The plot should look something like this.
# http://i.imgur.com/YzbWkHT.jpg.

ggplot(aes(x = cut, y = price/carat), data = diamonds) +
  geom_jitter(aes(color = color)) + facet_wrap(~ clarity) + 
  scale_color_brewer(type = 'div')
ggsave('lastone.png')
```

```{r}
# Gapminder Part 3

# To be completed. 
```

